### PR TITLE
doc for adding a new service to nordmart

### PR DESCRIPTION
**Pull request by kahootali**

### CODE REVIEW

**Comment by stakater-user** [comment]
@kahootali Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-47-1`

**Comment by stakater-user** [comment]
@kahootali Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-47-2`

**Comment by stakater-user** [comment]
@kahootali Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/stakater/job/Playbook/job/PR-47/3/) has Failed!

**Comment by stakater-user** [comment]
@kahootali Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-47-4`

**Review by usamaahmadkhan — APPROVED** [review]

**Pull request merged**
