### PR TITLE
Fix dockerfile permission

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/Playbook:SNAPSHOT-PR-94-90ec067c`

**Review by talha0324 — DISMISSED** [review]

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Playbook/commit/74bb33a4d377f73be7e72c59d1f75ddfcd218096/checks) has Failed!

**Review by stakater-user — APPROVED** [review]
Approved by @ahmedwaleedmalik

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Playbook/commit//checks) has Failed!

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker-openshift-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Playbook:v0.0.103`

**Pull request merged**
