### PR TITLE
add-cluster-deployment-docs`

### PR DESCRIPTION
**Pull request by aliartiza75**
This PR contains:

* Cluster creation guideline on AWS using Kops

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-2`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-3`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-4`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-5`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-6`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-7`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-8`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-9`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-10`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-11`

**Review by usamaahmadkhan — APPROVED** [review]

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-39-12`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
