### PR TITLE
Workshop konfigurator

### PR DESCRIPTION
**Pull request by usamaahmadkhan**

### CODE REVIEW

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-61-2`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-61-1`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-61-3`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-61-4`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-61-5`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-61-6`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-61-7`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-61-8`

**Review by aliartiza75 — APPROVED** [review]

**Pull request merged**
