### PR TITLE
update-playbook

### PR DESCRIPTION
**Pull request by aliartiza75**
1. update config.js 
2. remove chartmuseum manifest

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-76-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-76-2`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-76-3`

**Review by usamaahmadkhan — APPROVED** [review]

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-76-4`

**Pull request merged**
