### PR TITLE
[add-alerts-chart] 

### PR DESCRIPTION
**Pull request by aliartiza75**
update content/processes/alerting/slack-notifications-for-teams.md doc by adding a list of alerts

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-64-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-64-2`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-64-3`

**Review by rasheedamir — APPROVED** [review]
Looks good!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-64-4`

**Pull request merged**
