### PR TITLE
[add-sealed-secrets] 

### PR DESCRIPTION
**Pull request by aliartiza75**
add documentation regarding sealed secret workshop.

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-59-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-59-2`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-59-3`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-59-4`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-59-5`

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins.release.stakater.com/job/stakater/job/Playbook/job/PR-59/6/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-59-7`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-59-8`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-59-9`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-59-10`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-59-11`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
