### PR TITLE
[refactor-structure] 

### PR DESCRIPTION
**Pull request by aliartiza75**
add custom containers

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-78-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-78-2`

**Comment by aliartiza75** [comment]
@usamaahmadkhan kindly review it and merge it

**Review by rasheedamir — APPROVED** [review]

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-78-5`

**Pull request closed without merging**
