### PR TITLE
Added github actions workflow files

### PR DESCRIPTION
**Pull request by talha0324**

### CODE REVIEW

**Comment by stakater-user** [comment]
@talha0324 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/Playbook/commit/084227038d09861bdc6a0677e4492d611fba0ded/checks) has Failed!

**Comment by stakater-user** [comment]
@talha0324 Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-87-1`

**Comment by stakater-user** [comment]
@talha0324 Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/Playbook:SNAPSHOT-PR-87-a6d09727`

**Comment by stakater-user** [comment]
@talha0324 Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-87-2`

**Comment by stakater-user** [comment]
@talha0324 Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/Playbook:SNAPSHOT-PR-87-86b802b7`

**Review by ahmedwaleedmalik — DISMISSED** [review]
LGTM

**Comment by stakater-user** [comment]
@talha0324 Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/Playbook:SNAPSHOT-PR-87-e5e6176e`

**Review by ahmedwaleedmalik — APPROVED** [review]

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/Playbook:v0.0.92`

**Pull request merged**
