### PR TITLE
[fix-issue-in-playbook] update .vuepress/config.js

### PR DESCRIPTION
**Pull request by aliartiza75**

### CODE REVIEW

**Review by usamaahmadkhan — APPROVED** [review]

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-57-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-57-2`

**Comment by ahmadiq** [comment]
@aliartiza75 let's delete the branch since it has been merged already.

**Comment by aliartiza75** [comment]
@ahmadiq thank you for informing about the stale branch, I have deleted this branch.

**Pull request merged**
