### PR TITLE
Stakater Cluster Stacks docs

### PR DESCRIPTION
**Pull request by faizanahmad055**
This PR adds the documents for following stakater stacks. 
1. Global
2. Logging
3. Release

### CODE REVIEW

**Comment by stakater-user** [comment]
@faizanahmad055 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-3-1`

**Comment by stakater-user** [comment]
@faizanahmad055 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-3-2`

**Comment by stakater-user** [comment]
@faizanahmad055 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-3-3`

**Comment by stakater-user** [comment]
@faizanahmad055 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-3-4`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
