### PR TITLE
AKS cluster automation

### PR DESCRIPTION
**Pull request by usamaahmadkhan**

### CODE REVIEW

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-40-1`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-40-2`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-40-3`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-40-4`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-40-7`

**Comment by stakater-user** [comment]
@usamaahmadkhan Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-40-8`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
