### PR TITLE
Add tracing stack documentation

### PR DESCRIPTION
**Pull request by aliartiza75**

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-34-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-34-2`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-34-3`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-34-4`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-34-5`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-34-6`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-34-7`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-34-8`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
