### PR TITLE
Gitlab project

### PR DESCRIPTION
**Pull request by ahsan-storm**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahsan-storm Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-6-1`

**Comment by stakater-user** [comment]
@ahsan-storm Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-6-2`

**Comment by stakater-user** [comment]
@ahsan-storm Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-6-3`

**Comment by stakater-user** [comment]
@ahsan-storm Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/stakater/job/Playbook/job/PR-6/4/) has Failed!

**Comment by stakater-user** [comment]
@ahsan-storm Yikes! You better fix it before anyone else finds out! [Build 5](https://jenkins.release.stakater.com/job/stakater/job/Playbook/job/PR-6/5/) has Failed!

**Comment by stakater-user** [comment]
@ahsan-storm Yikes! You better fix it before anyone else finds out! [Build 6](https://jenkins.release.stakater.com/job/stakater/job/Playbook/job/PR-6/6/) has Failed!

**Comment by stakater-user** [comment]
@ahsan-storm Yikes! You better fix it before anyone else finds out! [Build 7](https://jenkins.release.stakater.com/job/stakater/job/Playbook/job/PR-6/7/) has Failed!

**Comment by stakater-user** [comment]
@ahsan-storm Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-6-8`

**Comment by stakater-user** [comment]
@ahsan-storm Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-6-9`

**Comment by rasheedamir** [comment]
@ahsan-storm plz discuss with @ahmadiq; this should be moved under versioning; as we will have fixed set of headings and things should be part of it

**Comment by stakater-user** [comment]
@ahsan-storm Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-6-11`

**Comment by stakater-user** [comment]
@ahsan-storm Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-6-12`

**Comment by ahsan-storm** [comment]
@rasheedamir discussed, and updated.

**Review by kahootali — APPROVED** [review]

**Pull request merged**
