### PR TITLE
monitoring-stack-documentation-in-playbook

### PR DESCRIPTION
**Pull request by aliartiza75**
I will add monitoring stack documentation in the playbook

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-26-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-26-2`

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/stakater/job/Playbook/job/PR-26/3/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-26-4`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-26-5`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
