### PR TITLE
Migration to vue 2.0

### PR DESCRIPTION
**Pull request by hussnain612**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Playbook:SNAPSHOT-PR-120-270e33ba`

**Comment by stakater-user** [comment]
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Playbook:SNAPSHOT-PR-120-7b753cb8`

**Comment by stakater-user** [comment]
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/playbook:SNAPSHOT-PR-120-b16820b9`

**Comment by stakater-user** [comment]
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/Playbook:SNAPSHOT-PR-120-b16820b9`

**Review by MuneebAijaz — APPROVED** [review]

**Comment by stakater-user** [comment]
@hussnain612 Image is available for testing. `docker pull docker-stakater-nexus.apps.prod.clusters.stakater.io/stakater/playbook:v0.0.117`

**Pull request merged**
