### PR TITLE
setting deploy option

### PR DESCRIPTION
**Pull request by ahmadiq**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmadiq Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/Stakater/job/Playbook/job/PR-2/1/) has Failed!

**Comment by rasheedamir** [comment]
@ahmadiq why did it fail?

**Comment by stakater-user** [comment]
@ahmadiq Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/Stakater/job/Playbook/job/PR-2/2/) has Failed!

**Comment by stakater-user** [comment]
@ahmadiq Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/Stakater/job/Playbook/job/PR-2/3/) has Failed!

**Comment by stakater-user** [comment]
@ahmadiq Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-2-4`

**Pull request merged**
