### PR TITLE
organize-playbook

### PR DESCRIPTION
**Pull request by aliartiza75**
Organize the Playbook structure by doing the following tasks:

* Add a new process in Playbook processes for cluster deployment on AWS and AZURE.
* Add stacks deployment documentation.
* Add gitlab pipeline configuration document.

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/stakater/job/Playbook/job/PR-38/4/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-38-5`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-38-6`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-38-7`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-38-8`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-38-9`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-38-10`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-38-11`

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 12](https://jenkins.release.stakater.com/job/stakater/job/Playbook/job/PR-38/12/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-38-13`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-38-14`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-38-15`

**Review by hamza3202 — APPROVED** [review]

**Pull request merged**
