### PR TITLE
[refactor-structure] refactor the documentation

### PR DESCRIPTION
**Pull request by aliartiza75**

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-2`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-3`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-4`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-5`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-6`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-7`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-8`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-9`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-10`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-11`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-12`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-13`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater/playbook:SNAPSHOT-PR-77-14`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
