### PR TITLE
[fix-package-version] 

### PR DESCRIPTION
**Pull request by aliartiza75**
bumped ecstatic version from 3.0.0 to 3.3.2
bumped js-yaml version from 3.9.0 to 3.13.0

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-33-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-33-2`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-33-3`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.release.stakater.com:443/stakater/playbook:SNAPSHOT-PR-33-4`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
